version: 2
jobs:
  pr:
    docker:
      - image: circleci/python:3.7
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: pip install -r requirements-ci.txt
      - run: black --check .
      - run: isort -c --df .
      - run: pycodestyle --max-line-length=120 .
workflows:
  version: 2
  pr:
    jobs:
      - pr:
          context:
            - dockerhub
          filters:
            branches:
              ignore: master

