name: Required Python style check

on:
  pull_request:
    branches:
      - master
    paths:
      - '**'

jobs:
  required-python-style-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: pip install -r requirements-ci.txt
    - name: Check by black
      run: black --check ./
    - name: Check by isort
      run: isort -c --df ./
    - name: Check by pycodestyle
      run: pycodestyle --max-line-length=120 ./
